- name: common
  hosts: common
  become: true

  roles:
    #- common
    #- sshd

- name: setting for web
  hosts: vagrant_web
  become: true

  roles:
    - nginx
    - git
    - rbenv
    - python

- name: setting for db
  hosts: vagrant_db
  become: true

  roles:
    - git
    - mongodb
