---
- name: pyenv | pyenv install check
  shell:  source ~/.bash_profile; which pyenv
  register: _pyenv_install_check
  failed_when: _pyenv_install_check.rc not in [ 0, 1]
  changed_when: false

- name: pyenv | git clone
  git:
    repo: git://github.com/pyenv/pyenv.git
    dest: /root/.pyenv
    accept_hostkey: yes
  when: _pyenv_install_check.rc == 1

- name: pyenv | edit .bash_profile
  blockinfile:
    dest: /root/.bash_profile
    content: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
  notify: source bash_profile
  when: _pyenv_install_check.rc == 1

- name: pyenv | prenv version check
  shell: bash -lc "pyenv versions | grep {{ python.version.xxx }}"
  register: _pyenv_version_check
  ignore_errors: yes
  changed_when: False
  when: _pyenv_install_check.rc == 1

- name: pyenv | pyenv install
  shell: bash -lc "pyenv install {{ python.version.xxx }}"
  when: _pyenv_version_check.rc == 1

- name: pyenv | set pyenv global version 
  shell: bash -lc "pyenv global {{ python.version.xxx }}"
  when: _pyenv_version_check.rc == 1

- set_fact: ansible_python_interpreter=/root/.pyenv/shims/python

- name: pyenv | pip
  pip:
    name: "{{ item }}"
  with_items:
    - pip_pkg
  ignore_errors: yes
  when: _pyenv_version_check.rc == 1

